version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
  node-app:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: docker-nodejs-mongodb
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    volumes:
      - /app/node_modules
      - .:/app
